### ISSUE TITLE
Implementing Android Keystore system

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me-android#1]
I spoke with @martijndoornik about Me using the app file store for storing the private key. When a mobile phone gets root on an android device, a malicious party can retrieve the *.key very easily.

We want to achieve a high level of security for the private key. We should store the key inside the android keystore, encrypted using the users finger print or a pincode.

A few libraries that enable usage of the keystore are:
java.security.KeyStore
android.security.keystore.KeyProperties
android.security.keystore.KeyGenParameterSpec

Libraries for generating keys:
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.IvParameterSpec

Some example implementation spec; I went through the code of uPort's implementation.
uPort uses the keystore and checks if the users device gots a fingerprint reader. If the device has one it prompts the user to use that for encrypting the privatekey, otherwise it uses sismple asymmetric protection.

## initiation of keystore object (ProtectedSharedPreferences.kt)
```kotlin
        private const val ANDROID_KEYSTORE_PROVIDER = "AndroidKeyStore"

        private fun getKeyStore(): KeyStore {
            // Get a KeyStore instance with the Android Keystore provider.
            val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE_PROVIDER)

            // Relict of the old JCA API - you have to call load() even
            // if you do not have an input stream you want to load - otherwise it'll crash.
            keyStore.load(null)
            return keyStore
        }
```

##  generation of key (ProtectedSharedPreferences.kt)
```kotlin
        fun genKey() {

            val keyStore = getKeyStore()

            val secretKey = keyStore.getKey(keyAlias, null) as SecretKey?
            if (secretKey == null) {

                val keyGenerator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE_PROVIDER)
                val purpose = KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                val builder = KeyGenParameterSpec.Builder(keyAlias, purpose)

                builder.setBlockModes(BLOCK_MODE)
                        .setKeySize(256)
                        .setEncryptionPaddings(BLOCK_PADDING)

                keyGenerator.init(builder.build())

                keyGenerator.generateKey()
            }
        }
```

# Resources:
https://developer.android.com/training/articles/keystore

https://github.com/uport-project/uport-android-signer/blob/master/signer/src/main/java/com/uport/sdk/signer/storage/ProtectedSharedPreferences.kt

https://github.com/uport-project/uport-android-signer/blob/master/signer/src/main/java/com/uport/sdk/signer/UportSigner.kt

**Comment by kremlinwarrior** [comment]
Don't delete this issue. In the new version this is the reminder to add keystore

**Comment by maxvisser** [comment]
yes this should probably be implemented after august

**Comment by kremlinwarrior** [comment]
I've implemented this yesterday =)

**Comment by maxvisser** [comment]
Cool, could you give me a hand in finding it within the code? I want to check it out :)

**Comment by kremlinwarrior** [comment]
But it has bugs with private key as encryption database key. (we should check it next week)

We encrypt all main.db file with all users data

https://github.com/initflow/me-android/commit/cb68cbc8cff611647dfc209c8beb6b33cd99d16a
https://github.com/initflow/me-android/commit/fc866e2b3e2aae396d06bba488a4dab987f567ff

**Comment by maxvisser** [comment]
https://github.com/initflow/me-android/commit/fc866e2b3e2aae396d06bba488a4dab987f567ff#r29733491

**Comment by jknnr** [comment]
Implemented
