### ISSUE TITLE
Change the starting screen notification "restore account"

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-android#20]
1. Starting screen gives the option "restore account".

--------------------------------

1. Should be alligned with iOS

	- English: "Log in with existing account"
	- Dutch: "Ik heb een me identiteit"

**Comment by maxvisser** [comment]
Dutch: "Log in met een bestaand account" is maybe a better translation

**Comment by GerbenBosschieter** [comment]
@maxvisser I agree , better use that sentence

**Comment by jknnr** [comment]
done
