### ISSUE TITLE
Change notification QR-Code after loggin in to one the dashboards

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me-android#21]
1. After you've logged in to one the dashboards the QR-Code scanner gives the notification: "Identity Restored"

--------------------------------

1. Notification should be something like:

	- English: "You have successfully logged in"
	- Dutch: "Je bent succesvol ingelogd"

**Comment by maxvisser** [comment]
should choose between 'u' and 'je' for dutch translation. Reminder for our meeting about translations.

**Comment by jknnr** [comment]
Done with Je. Reopen after the meeting if needed:)
