### ISSUE TITLE
Texts of the fields that need to be filled in while registering are in english should be in Dutch.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me-android#30]
They do not seem to take on the language of the phone.

**Comment by maxvisser** [comment]
need to be added to strings.xml

**Comment by iNomaD** [comment]
Please, help me to find a proper translation for them:
```
    <string name="new_account_field_email">E-mail</string>
    <string name="new_account_field_first_name">Given Name</string>
    <string name="new_account_field_last_name">Family Name</string>
    <string name="new_account_field_bsn">BSN</string>
    <string name="new_account_field_phone">Phone number</string>
```

**Comment by jknnr** [comment]
<string name="new_account_field_email">E-mail</string>
    <string name="new_account_field_first_name">Voornaam</string>
    <string name="new_account_field_last_name">Achternaam</string>
    <string name="new_account_field_bsn">BSN</string>
    <string name="new_account_field_phone">Telefoonnummer</string>

**Comment by iNomaD** [comment]
done

**Comment by jknnr** [comment]
done
