### ISSUE TITLE
No feedback on second submission of pascode.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me-android#32]
I have to fill in my passcode twice. I know I have to do it but it is not clearly shown when I reach the second time filling in the passcode.

**Comment by iNomaD** [comment]
The title of the screen changes from "Inlogcode instellen"(Create passcode) to "Bevestig inlogcode"(Confirm passcode). Isn't it?

**Comment by maartenfv** [comment]
Checked it! @iNomaD It works. This issue can be closed!
