### ISSUE TITLE
When clicking on recovery link twice it sends me to a strange website

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me-android#38]

**Comment by TomForus** [comment]
When clicking on the link twice it sends you to this site.



![double click restore issue 2](https://user-images.githubusercontent.com/36765624/46957732-787f1180-d098-11e8-9523-6233bf27f6f9.png)
![double click restore issue](https://user-images.githubusercontent.com/36765624/46957733-787f1180-d098-11e8-821c-05635e979c3f.png)

**Comment by maxvisser** [comment]
This will be fixed by implementing mail notifications. I will close this for now.
