### ISSUE TITLE
Sign up, create account button overlapping

### ISSUE THREAD

**Issue by cgomezmendez** [teamforus/me-android#43]
![device-2018-10-19-023835](https://user-images.githubusercontent.com/2073238/47201510-206e3680-d348-11e8-8f0f-59f304f22d1c.png)
As you can see in the attached picture, the create account button is over the form, it shouldn't really be moving with the keyboard I think, but I don't know if that's the expected behaviour.

**Comment by maxvisser** [comment]
Looks weird to be honest.  @jknnr 

I like it though that it sticks to the bottom even if you have more input fields. But now when we only have 3 fields is a overkill

**Comment by iNomaD** [comment]
fixed
